springdoc.swagger-ui.path: /swagger-ui.html

logging.level.org.springframework.jdbc.core: DEBUG
spring:
  datasource:
    url: jdbc:sqlserver://yauheniy-lepkovich-azure-learning.database.windows.net:1433;database=yl-azure-learning-sql-db;user=yauheniy-lepkovich-admin@yauheniy-lepkovich-azure-learning;password=ylmysql123!@#;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: yauheniy-lepkovich-admin
    password: ylmysql123!@#
  jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

hello-world-message: hello world!